### ISSUE TITLE
dual http parsers

### ISSUE THREAD

**Issue by Frost** [Frost/hink#32]
Hink is by some reason using both `httparty` and `mechanize`. That's probably redundant, and should be fixed by making all plugins use the same parser.

**Comment by Frost** [comment]
It seems like the only plugin using `httparty` is the github plugin, so that one should probably be converted to use `mechanize` instead.

**Comment by Koronen** [comment]
So this is not fixed? Accidental close, maybe?

**Comment by Frost** [comment]
More like "Oh, I forgot to close this when I removed the `httparty` dependency about two months ago (in db09f519e502d9480ca95925f15e59b534193960)".

**Comment by Koronen** [comment]
Ah.
