### ISSUE TITLE
Add GitHub interface

### ISSUE THREAD

**Issue by Koronen** [Frost/hink#5]
> 13:08:07       @Frost | och jag kanske borde lägga till så att man kan be fråga vad någon given issue är...
> 13:08:10       @Frost | det vore awesome
> 13:08:14       @Frost | en github-modul alltså
> 13:08:25       @Frost | kanske inte härinne, men i #ior

Add an interface to GitHub. It would be nice to be able to check issues, for instance.

**Comment by Koronen** [comment]
The gem @fcoury/octopi might be useful.

**Comment by Frost** [comment]
Yes, apart from the fact that the GitHub API is at version 3 now, and that gem is for version 2. More info here: http://develop.github.com/p/issues.html

**Comment by Koronen** [comment]
What about @jwilger/github-v3-api?

**Comment by jwilger** [comment]
@jwilger/github-v3-api is nowhere near complete. I've been hacking on it as part of another side project. I made it a separate gem early on, but then found it was easier to work on in the context of the other project (just for workflow). I will extract the changes back into a the github-v3-api once there's a bit more of a walking skeleton. I'll happily take pull-requests on it, though, if someone wants to hack on it. I'm even open to changes in the architecture of it. Main thing it _must_ support is using OAuth2 to authenticate all actions.
